// <auto-generated />
using MemberTracking.Data.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemberTracking.Migrations
{
    [DbContext(typeof(MemberDbContext))]
    partial class MemberDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MemberTracking.Data.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Kara",
                            LastName = "Sullivan",
                            MiddleName = "Percival"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Stephen",
                            LastName = "Hollinden",
                            MiddleName = "Maxwell"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Caldwell",
                            LastName = "Crawford",
                            MiddleName = "Cooper"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Mary",
                            LastName = "Richter",
                            MiddleName = "Sue"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Elisabeth",
                            LastName = "Scott",
                            MiddleName = "Walder"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Michael",
                            LastName = "Charles",
                            MiddleName = "Utrauer"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Charlotte",
                            LastName = "Wilson",
                            MiddleName = "Alice"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "James",
                            LastName = "Anderson",
                            MiddleName = "Edward"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Ahmed",
                            LastName = "Kumar",
                            MiddleName = "Yan"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Nushi",
                            LastName = "Huang",
                            MiddleName = "Li"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
